/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifsc.projetopedrapapeltesoura;

import java.util.ArrayList;
import java.util.Locale;
import java.util.Random;
import java.util.ResourceBundle;

/**
 *
 * @author Aluno
 */
public class MenuJFrame extends javax.swing.JFrame {

    public String respostaJogador = null; 
    
    public static String idioma = null;
    public static String pais = null;
        
    public static Locale locale =  null;
    public static ResourceBundle traducoes = null;        
        
    /**
     * Creates new form MenuJFrame
     */
    public MenuJFrame(String resposta) {
        initComponents();
         
        
        
        if(idioma == null && pais == null){
            idioma = new String("pt");
            pais = new String("BR");
        }
        
        locale = new Locale(idioma, pais);
        traducoes = ResourceBundle.getBundle("MessagesBundle", locale);    
      
        
      
        if(resposta != null || resposta != ""){
        
            tfResultadoJogardor.setText(resposta);
            respostaJogador = resposta;
        }
        tfResultadoSistema.setVisible(false);
        
        jLabel1.setText(traducoes.getString("LB_TITULO"));
        jLabel3.setText(traducoes.getString("LB_ESC_USUARIO"));
        jLabel4.setText(traducoes.getString("LB_ESC_SISTEMA"));
        btOptions.setText(traducoes.getString("BT_OPCAO"));
        btJogar.setText(traducoes.getString("BT_JOGAR"));
        jLResultadoJogo.setText(traducoes.getString("LB_RESULTADO"));       
        
        popularComboBoxIdioma();
    }
    
    private void popularComboBoxIdioma(){
        ArrayList<String> idiomas = new ArrayList<>();
        idiomas.add(traducoes.getString("ESCOLHA_IDIOMA"));
        idiomas.add(traducoes.getString("PORTUGUES"));
        idiomas.add(traducoes.getString("INGLES"));
        idiomas.add(traducoes.getString("ESPANHOL"));
        
        for (String idioma : idiomas) {
            comboBoxLinguagem.addItem(idioma);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btOptions = new javax.swing.JButton();
        tfResultadoJogardor = new javax.swing.JLabel();
        btJogar = new javax.swing.JButton();
        jLResultadoJogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfResultadoSistema = new javax.swing.JLabel();
        comboBoxLinguagem = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 200));
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Bem Vindos ao Jogo de Pedra Papel Tesoura");

        btOptions.setText("ESCOLHER OPÇÃO");
        btOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOptionsActionPerformed(evt);
            }
        });

        tfResultadoJogardor.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        tfResultadoJogardor.setText("Resultado");

        btJogar.setText("Jogar");
        btJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJogarActionPerformed(evt);
            }
        });

        jLResultadoJogo.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLResultadoJogo.setText("Resultado");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel2.setText("X");

        jLabel3.setText("Escolha do usuário");

        jLabel4.setText("Escolha do sistema");

        tfResultadoSistema.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        tfResultadoSistema.setText("Resultado ");

        comboBoxLinguagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxLinguagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(tfResultadoJogardor)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tfResultadoSistema)
                        .addGap(75, 75, 75))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLResultadoJogo)))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboBoxLinguagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btOptions)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(tfResultadoJogardor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(tfResultadoSistema))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLResultadoJogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxLinguagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOptionsActionPerformed
        OpcoesJFrame frame = new OpcoesJFrame();
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btOptionsActionPerformed

    private void btJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJogarActionPerformed
        JogadasSistema jogo = new JogadasSistema();
        
        String[] array = jogo.Jogar(respostaJogador);
        
        if(array != null){
            String resultadoJogo = array[0];
        
            String valorDoSistema = array[1];

            if(resultadoJogo != null){
                jLResultadoJogo.setText(resultadoJogo);
            }

            if(valorDoSistema!= null){
                tfResultadoSistema.setVisible(true);
                tfResultadoSistema.setText(valorDoSistema);
            }
        }
    }//GEN-LAST:event_btJogarActionPerformed

    private void comboBoxLinguagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxLinguagemActionPerformed
        if(comboBoxLinguagem.getSelectedIndex() == 1){
            idioma = new String("pt");
            pais = new String("BR");
            
            this.dispose();
            MenuJFrame frame = new MenuJFrame(" ");
            frame.setVisible(true);
        }
        else if(comboBoxLinguagem.getSelectedIndex() == 2){
            idioma = new String("en");
            pais = new String("US");
            
            this.dispose();
            MenuJFrame frame = new MenuJFrame(" ");
            frame.setVisible(true);
        }
        else if(comboBoxLinguagem.getSelectedIndex() == 3){
            idioma = new String("es");
            pais = new String("ES");
            
            this.dispose();
            MenuJFrame frame = new MenuJFrame(" ");
            frame.setVisible(true);
        }
        
    }//GEN-LAST:event_comboBoxLinguagemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuJFrame(" ").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btJogar;
    private javax.swing.JButton btOptions;
    private javax.swing.JComboBox<String> comboBoxLinguagem;
    private javax.swing.JLabel jLResultadoJogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel tfResultadoJogardor;
    private javax.swing.JLabel tfResultadoSistema;
    // End of variables declaration//GEN-END:variables
}
